name: "Code style & tests"
on:
  pull_request:
    # Run this workflow for all PRs against main
    branches:
      - main

jobs:
  php-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer-command:
          - name: Code Style
            command: 'cs:check'
          - name: Composer normalize
            command: 'normalize --dry-run'
          - name: PHPStan
            command: analyze
          - name: PHPUnit
            command: test:unit
          - name: Rector
            command: 'rector -- --dry-run'

    name: ${{ matrix.composer-command.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install composer dependencies
        run: composer install

      - name: 'Run check "${{ matrix.composer-command.name }}"'
        run: composer ${{ matrix.composer-command.command }}
